name: Go CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod tidy

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Run tests and generate JUnit report
        run: |
          mkdir -p reports
          go test -v 2>&1 | go-junit-report > reports/junit.xml

      - name: Install Python and junit2html
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install junit2html

      - name: Convert JUnit report to HTML
        run: junit2html reports/junit.xml reports/test-report.html

      - name: Upload test report artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: reports/test-report.html

      - name: Run linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./...

      - name: Run static analysis
        run: go vet ./...

      - name: Send report to Slack
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          TOKEN="${SLACK_API_TOKEN}"
          REPORT_FILE="reports/test-report.html"
          CHANNEL_ID="C06SKBT3ZU5"  # Cambia esto al ID del canal de Slack al que deseas enviar el archivo

          curl -F "token=$TOKEN" -F "channels=$CHANNEL_ID" -F "file=@$REPORT_FILE" -F "title=Test Report" https://slack.com/api/files.upload
