name: Go CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod tidy

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      - name: Run tests and generate JUnit report
        run: |
          mkdir -p reports
          go test -v 2>&1 | tee reports/test-output.txt | go-junit-report > reports/junit.xml
      - name: Install Python and junit2html
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install junit2html

      - name: Convert JUnit report to HTML
        run: junit2html reports/junit.xml reports/test-report.html

      - name: Run linter
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./... 2>&1 | tee -a reports/test-output.txt

      - name: Run static analysis
        run: go vet ./... 2>&1 | tee -a reports/test-output.txt

      - name: Filter and send errors to Slack
        if: always() 
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          TOKEN="${SLACK_API_TOKEN}"
          ERROR_LOG="reports/test-output.txt"
          FILTERED_ERROR_LOG="reports/filtered-errors.txt"
          CHANNEL_ID="C072KA9KKPD"  # Cambia esto al ID del canal de Slack al que deseas enviar el archivo
          
          # Filtrar errores
          grep -E '(ERROR|FATAL)' "$ERROR_LOG" > "$FILTERED_ERROR_LOG"
          
          # Enviar errores a Slack junto con un mensaje
          MESSAGE="Se encontraron errores durante la ejecución del pipeline. Revisa el archivo adjunto para más detalles."
          curl -F "token=$TOKEN" -F "channels=$CHANNEL_ID" -F "file=@$FILTERED_ERROR_LOG" -F "initial_comment=$MESSAGE" -F "title=Error Log" https://slack.com/api/files.upload
